# JVM 内存加大，MediaPipe 编译需要
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# AndroidX
android.useAndroidX=true
# Kotlin 代码风格
kotlin.code.style=official
# 非传递型 R class 加快构建
android.nonTransitiveRClass=true
# 项目路径含中文，绕过 AGP 的非 ASCII 路径检查
# 官方说明：http://b.android.com/95744
android.overridePathCheck=true
